### ISSUE TITLE
Pedant link not up to date

### ISSUE THREAD

**Issue by Eradash** [thomper/sweet-alert-dialog#5]
The http://www.pedant.cn link in the description and README is no longer related to the project. Since you have a working repo, and even the original repo issues links to yours, it could be nice to remove the link to this site ;)

**Comment by thomper** [comment]
Good idea!

I have made this change on master and updated the github description.  The author appears to still be around, perhaps just too busy to update this library (you can see they were active on Github in early 2018), so I've put links to their github page instead.

I left it in the licence since that's not to be changed and github doesn't make the link in the licence clickable anyway.

Everyone should move to F0RIS' fork of this library though because they're actively maintaining it: https://github.com/F0RIS/sweet-alert-dialog
